### ISSUE TITLE
Video goes slow like cut

### ISSUE THREAD

**Issue by mipalitroche** [popcorn-official/popcorn-desktop#122]
#### Operating System Version:

Windows 10 with intel i7-4710hq
#### Popcorn Time Version:

0.3.9
#### Download date:

03/21/2016
#### Expected Behaviour

To run ok with any graphics card
#### Actual Behaviour

When I watch a movie it goes slow like cut whenever I move the cursor, after a while it crashes and there's no image at all. If I stop moving the cursor it goes ok, but if I move it again it starts again. It only happens with the integrated graphics card (i7-4710hq) but it doesn't with the GPU Nvidia GTX 960m.
#### Steps to repoduce the behaviour

1. Open the app
2. Select the movie
3. (When it is playing) Move the cursor

**Comment by ChrisAlderson** [comment]
Cannot reproduce
