### ISSUE TITLE
indie

### ISSUE THREAD

**Issue by kotenok2000** [popcorn-official/popcorn-desktop#1398]
Operating System Version:

Microsoft Windows [Version 10.0.18363.778]
Popcorn Time Version:

0.4.4-0
Download date:

#### Expected Behaviour

.Show indie tab

#### Actual Behaviour

does not show  indie tab

#### Steps to reproduce the behaviour

1. Install 0.3.10 version from https://ci.popcorntime.app/job/Popcorn-Time-Desktop/200/artifact/build/Popcorn-Time-0.3.10-win64-Setup.exe
2.  Indie tab is present.
3. Update to 0.4.4-0
4. Indie tab is missing.

**Comment by kiriles90** [comment]
the indie tab got removed for good

@Persei08 close please
