### ISSUE TITLE
search does not work with incomplete words

### ISSUE THREAD

**Issue by kotenok2000** [popcorn-official/popcorn-desktop#1456]
Operating System Version:

Windows 10
Popcorn Time Version:

0.4.4-0
Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...The app   does not search for incomplete  words
#### Steps to reproduce the behavior

1. ...Enter matrix into search bar. it finds 3 movies
2. ... enter "matr" into search bar. it does not find anything
3. ...

**Comment by kotenok2000** [comment]
will it be fixed?

**Comment by Persei08** [comment]
not an app issue, the app don't make the search, it sent the searched term to api and display the results.

It's more a feature to ask on popcorn-api repo.

**Comment by kotenok2000** [comment]
Opened issue there
https://github.com/popcorn-official/popcorn-api/issues/140

**Comment by Persei08** [comment]
Thx ;)

**Comment by nad182** [comment]
As mentioned in https://github.com/popcorn-official/popcorn-api/issues/140#issuecomment-1909282128, it seems like this issue has been fixed at some point, though I'm not sure who the current maintainers are to close that issue as "completed".

**Comment by kotenok2000** [comment]
Will do it myself.
