### ISSUE TITLE
Wrong episode is shown

### ISSUE THREAD

**Issue by kotenok2000** [popcorn-official/popcorn-desktop#1477]
Operating System Version:

Windows
Popcorn Time Version:

0.3.10 28112f67
Download date:

Download url (optional):

#### Expected Behaviour

...
Show  me Doctor Who episode rose
#### Actual Behaviour

...
 It shows me Doctor.Who.Extra.S01E01.Deep.Breath.720p.Webrip.x264-C4TV
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot of error from developer console (optional)

![Снимок экрана (46)](https://user-images.githubusercontent.com/8822292/82729888-24242500-9d04-11ea-90ff-9ea94e8e9bdd.png)

**Comment by Persei08** [comment]
This is not an error with popcorntime desktop but more something with the way popcorn-api works and the fact that eztv have added this episode to Doctor who episodes list.

Your screenshot here isn't really helpful there is nothing in it which could explain your issue, it just show an error with MPC icon and that you play a torrent in MPC.


If you want, you can make a report at [popcorn-api repo](https://github.com/popcorn-official/popcorn-api), but here I will close it.
