### ISSUE TITLE
This shitty Pop-corn app doesn't show me where the downloaded movie saved. No down location in the app too. What kinda crap is this app? Developed by a brainless moron?

### ISSUE THREAD

**Issue by Danu93** [popcorn-official/popcorn-desktop#1509]
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Danu93** [comment]
Downloaded a movie yesterday and showed progress is 100%. And Can't find to which location it downloaded. Can't see down record after closing it? I thought people who develop these apps have brains. Seems they are just code jokies who doesn't have common sense

**Comment by Persei08** [comment]
What is more useful, trash talking contributors/developers or sending a patch?
