### ISSUE TITLE
update seeding  creates lots of errors

### ISSUE THREAD

**Issue by kotenok2000** [popcorn-official/popcorn-desktop#1522]
Operating System Version:

windows 10 2004
Popcorn Time Version:

https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/
Download date:

today
Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

... 
 when i activated update seeding i started getting errors in console
#### Steps to reproduce the behaviour

1. ... activate update seeding 
2. ... restart the app 
3. ...

#### Screenshot of error from developer console (optional)

![Снимок экрана (49)](https://user-images.githubusercontent.com/8822292/84541855-e44bce80-ad00-11ea-9579-25735989fd7e.png)

seedbox.js:228 Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\frolo\AppData\Local\Temp\Popcorn-Time/TorrentCache/01610ba9e5108b88fff1eb675c1ce0a3d2f84726'

**Comment by dutchy1001** [comment]
I don't have the default folder and I don't get this error when turning on the seeding. just the message in console "Seeding the Current Update!"
Do you have a firewall set that prevent outgoing traffic?

**Comment by kotenok2000** [comment]
it happens when i restart popcorn time after  enabling update seeding.
 did you mean this folder? C:\Users\username here\AppData\Local\Popcorn-Time\User Data\Default

**Comment by dutchy1001** [comment]
I've enabled the seeding, restarted PCT and will let it run for a while to see if the error will appear to confirm this.

**Comment by kotenok2000** [comment]
Can you look at ram consumption too?

**Comment by dutchy1001** [comment]
when idle my ram use is around the 260mb and when "console" is open it will be around the 325mb. It goes up and down but stays around those figures.

So far no error for the seeding issue you have.

**Comment by dutchy1001** [comment]
at least 50 minutes running PCT (idle) and still no seeding error.

**Comment by saxobroko** [comment]
Getting the same error
![image](https://user-images.githubusercontent.com/18757374/89521177-639de000-d822-11ea-8fba-5a4b9ce418d4.png)
![image](https://user-images.githubusercontent.com/18757374/89521230-76181980-d822-11ea-8863-273a7f8c19b6.png)

**Comment by dutchy1001** [comment]
@saxobroko what version do you use of PCT?

**Comment by saxobroko** [comment]
> @saxobroko what version do you use of PCT? 

0.4.4-0

**Comment by dutchy1001** [comment]
@saxobroko that still doesn't say much as all (dev) builds are 0.4.4.

Were did you download from? Was it a dev build (if so what build number)or from th main PCT page. 

Sinse the OP posted there have been multiple dev builds updates, does the latest one has the same issue?

**Comment by saxobroko** [comment]
> @saxobroko that still doesn't say much as all (dev) builds are 0.4.4.
> 
> 
> 
> Were did you download from? Was it a dev build (if so what build number)or from th main PCT page. 
> 
> 
> 
> Sinse the OP posted there have been multiple dev builds updates, does the latest one has the same issue?
> 
> 
> 
> 

I'm pretty sure i downloaded this from GitHub but build number is b2007344

**Comment by dutchy1001** [comment]
OK, you have build 413 (latest build is 429). Many things have been changed and updated sinse. Get the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** and see if the issue is still there then.

let us know how you get on...

**Comment by saxobroko** [comment]
> OK, you have build 413 (latest build is 429). Many things have been changed and updated sinse. Get the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** and see if the issue is still there then.
> 
> let us know how you get on...

Alright downloaded latest one from there (4th August) and still getting same error
![image](https://user-images.githubusercontent.com/18757374/89601238-67c01100-d8a7-11ea-9a73-68531af6ebc8.png)

**Comment by kiriles90** [comment]
Can everyone try build 443 if you want and check if the issue still exists?

**Comment by kotenok2000** [comment]
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/ only has 442nd build

**Comment by kiriles90** [comment]
Yeah I mean when its out. Should be soon, today/tomorrow.

**Comment by Persei08** [comment]
[Dev build #443 is available](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastSuccessfulBuild/)
