### ISSUE TITLE
issues with only movies not loading 

### ISSUE THREAD

**Issue by Jimy-Salem** [popcorn-official/popcorn-desktop#1646]
Operating System Version: 10.15.2 Mac
Popcorn Time Version: 4.4
Download date: 2 Aug 2020

The app is loading the series, animes but not the movies
What's wrong

**Comment by dutchy1001** [comment]
Update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**. If that doesn't resolve your issue report back, if it does close this issue please.
