### ISSUE TITLE
episodes never start streaming

### ISSUE THREAD

**Issue by carolinapellegrino** [popcorn-official/popcorn-desktop#2019]
Operating System Version:
 windows 10

Popcorn Time Version:
 love in the time of corona beta

Download date:

Download url (optional):

#### Expected Behaviour

... start streaming episodes as soon as clicked on watch on popcorntime

#### Actual Behaviour

... 1. ... episode 4 from 911 lone star never starts to stream
2. ... episode 4 from season 4 of 911 never starts to stream
3. ...  episode 5 from season 4 of the resident never starts to sream

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/78914451/107644375-1e85bb00-6c56-11eb-8f39-492422d857f4.png)

![image](https://user-images.githubusercontent.com/78914451/107644279-fe55fc00-6c55-11eb-898e-264dd8fe8502.png)

**Comment by kiriles90** [comment]
Update to the latest build from ci.popcorntime.app and the 'Watch Now' button will work normally again. Normally being the UI will respond nomatter if the torrent you are trying to stream/download has seeds or no. Ofc torrents with no seeds will still wont be able to connect so in those cases use the Torrent Collection tab to find a different torrent or just import one from anywhere you want. (drag&drop the .torrent file or magnet link in Popcorn Time)
