### ISSUE TITLE
show is stuck on 'connecting' after pressing 'watch now'

### ISSUE THREAD

**Issue by sazenator** [popcorn-official/popcorn-desktop#2113]
Operating System Version:
windows 10 (64bits?)

Popcorn Time Version:
Build #458 
0.4.4 beta (739ad0ac)

Download date:
this version on 21st of April 2021

Download url (optional):
https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastStableBuild/
(I think)

#### Expected Behaviour
When selecting watch now on an episode of a show, it is expected that it will start connecting and downloading. After that the episode should be starting to play.

#### Actual Behaviour
instead of starting to download, it stayed on 'connecting' nothing happened, not even after a while. My WIFI connection was sufficient and the problem does not occure with other shows. (with me, The Vampire Diaries has this problem)

#### Steps to reproduce the behaviour

1. Select 'the vampire diaries' in de series tab
2. Select the first episode of the show
3. Select 'watch now'
4.  (if the same problem occures, you wil see the loading screen that says and stays on 'connecting'

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://user-images.githubusercontent.com/82974834/115615840-c28f8080-a2ef-11eb-9f97-6946f9ba5afc.png)

![image](https://user-images.githubusercontent.com/82974834/115616043-01bdd180-a2f0-11eb-8f63-e07ee3efd128.png)

**Comment by kiriles90** [comment]
Popcorn Time is a torrent client. If whatever you are trying to stream doesnt have enough seeds it wont connect. Select a different quality, use the Torrent Collection tab, or drag&drop a torrent/magnet link in from anywhere you want. (one with better health)
