### ISSUE TITLE
Cannot stream to LG/Samsung Smart TVs.

### ISSUE THREAD

**Issue by reiazevedo** [popcorn-official/popcorn-desktop#2677]
Operating System Version:
Windows 11

Popcorn Time Version:

0.4.9

Download date: 22/12/2022

Expected Behaviour

Both my LG and Samsung TV show up for me to stream to. I try clicking on either one of them. The app says it's streaming to the TV.

Actual Behaviour

Nothing happens on the TV side. On the console, I get this:

![image](https://user-images.githubusercontent.com/42376982/209200305-6a732262-37a1-4a50-bb1f-0c59abb4a3ca.png)

Steps to reproduce the behaviour

1 - Choose any movie/series
2 - Select either my LG or Samsung TVs to stream to
3 - Click on play

**Comment by kiriles90** [comment]
Dont use the Airplay function of your devices. Support is buggy due to apple's various roadblocks. Use DLNA or Chromecast instead. Open issue about Airplay at https://github.com/popcorn-official/popcorn-desktop/issues/1433 so closing this but comment below normally if you need something else.
