### ISSUE TITLE
popcorntime not working

### ISSUE THREAD

**Issue by 10Kevinho10** [popcorn-official/popcorn-desktop#3034]
![Schermopname (1)](https://github.com/user-attachments/assets/96c2667e-b927-4f47-a142-18db55bec085)
![Schermopname (2)](https://github.com/user-attachments/assets/a9f07716-6f66-4109-b647-10c5ae694924)
![Schermopname (3)](https://github.com/user-attachments/assets/a3b24bcd-de88-4280-a3e7-79aa32c930fe)
Popcorntime not working anymore,

Since popcorn cant update the API servers anymore automaticly
its not working anymore.
Yesterday i could get it to work for a little bit by changing the servers manualy.
but now that does not work anymore.
I cant download or watch anything.
Its like it does not have peers en seeders anymore.
Are there more people that have this issues,  or anyone with a solution how i can make it 
work again.?

**Comment by 10Kevinho10** [comment]
ok,, for anyone that encounters the problem.
I enebled the auto update function.
and this works for the moment.

**Comment by merseyV** [comment]
.... voodoo! 🤣

**Comment by merseyV** [comment]
.... it's voodoo!! 😆

**Comment by shimjitsu** [comment]
doesn't work at the moment, an update is required. I have added the API links manually.

**Comment by dutchy1001** [comment]
opened a new bug report to consolidate this topic and #3030

Closing this
