### ISSUE TITLE
Automatically update API's server URL's not working

### ISSUE THREAD

**Issue by dutchy1001** [popcorn-official/popcorn-desktop#3035]
#### Operating System Version:

seems to affect all Operating Systems
#### Popcorn Time Version:

version 0.5.1 and before

#### Download date:

N/A
#### Download url:

N/A
#### Expected Behaviour:

when clicking to refresh API's in settings an update to the API's with a message for succesful update
#### Actual Behaviour:

It gives error message the update failed
#### Steps to reproduce the behaviour:

1. Open PCT and go to settings, scroll down to "API Server(s)"
2. Click icon to update/refresh the API's
3. After a few the error message appears

talked about this in #3030 and simular as #3034

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

N/A

**Comment by merseyV** [comment]
>**Steps to reproduce the behaviour:**

Or download/make a new/clean install of any Popcorntime version (with the automatically update API feature). Accept (ticked) default options  on the "Terms and Conditions" window:

<img width="1334" alt="Please wait" src="https://github.com/user-attachments/assets/6cb7f228-56e9-41e4-8510-d99add6847a1">


<img width="1330" alt="Error" src="https://github.com/user-attachments/assets/a4b6d9d5-4966-463d-83c2-f0d996e82713">

Manual/custom update of the API's ... `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/ ` are not saved to "dhtInfo"/"dhtData" values in the appdata 'settings db" file: So will not appear in the API address (drop-lists) .. and it will throw a transient "Error" message every time PTapp is rebooted?

<img width="1332" alt="manual API's" src="https://github.com/user-attachments/assets/0c1b4876-b224-4dba-86b1-16f46a93d49a">

**Comment by merseyV** [comment]
>**Steps to reproduce the behaviour:**

Or download/make a new/clean install of any Popcorntime version (with the automatically update API feature). Accept (ticked) default options  on the "Terms and Conditions" window:

<img width="1334" alt="Please wait" src="https://github.com/user-attachments/assets/6cb7f228-56e9-41e4-8510-d99add6847a1">


<img width="1330" alt="Error" src="https://github.com/user-attachments/assets/a4b6d9d5-4966-463d-83c2-f0d996e82713">

Manual update of the API's: 
`https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`  
are not saved to "dhtInfo"/"dhtData" values in the appdata 'settings db" file: So will not appear in the API address (drop-down lists) .. and it will throw a transient "Error" message every time PTapp is rebooted?

<img width="1333" alt="Manual update" src="https://github.com/user-attachments/assets/b94ec8cc-9160-4f7c-b34d-78d0d8569296">

**Comment by merseyV** [comment]
>**Steps to reproduce the behaviour:**

Or, download/make a new/clean install of any Popcorntime version (with the automatically update API feature). Accept (ticked) default options  on the "Terms and Conditions" window:

<img width="1334" alt="please wait" src="https://github.com/user-attachments/assets/f6ac9584-fd4f-461c-aaae-1ed9aed5bd2e">

<img width="1330" alt="Error" src="https://github.com/user-attachments/assets/f9a813c5-885e-423c-89d3-8fb5e392b5dd">



A manual update of the API's will be saved as "custom" values in the 'settings.db' and loaded when PTapp reboots.
`https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`  
A successful Auto-update produces "dhtInfo"/"dhtData" values in the appdata 'settings db" file: Consequently, manual inputs will not appear in the API address (drop-down lists) .. and it will throw a transient "Error" message every time PTapp is rebooted?

<img width="1333" alt="Manual API" src="https://github.com/user-attachments/assets/452d6b81-5015-4902-924a-39258e18289a">


<img width="1124" alt="settings db" src="https://github.com/user-attachments/assets/fd973063-0d69-4e72-a98c-b1d65a614265">

**Comment by grimy86** [comment]
> > **Steps to reproduce the behaviour:**
> 
> Or, download/make a new/clean install of any Popcorntime version (with the automatically update API feature). Accept (ticked) default options on the "Terms and Conditions" window:
> 
> <img alt="please wait" width="1334" src="https://private-user-images.githubusercontent.com/137357177/358936881-f6ac9584-fd4f-461c-aaae-1ed9aed5bd2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTQ0OTEsIm5iZiI6MTcyNDM1NDE5MSwicGF0aCI6Ii8xMzczNTcxNzcvMzU4OTM2ODgxLWY2YWM5NTg0LWZkNGYtNDYxYy1hYWFlLTFlZDlhZWQ1YmQyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxOTE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2Y2YTRmZjE0N2MxYWM3Njk2YzlkZGQxODJiZDg5NWNlMzIxYjRmNjEzZjVlNWE4OWVlMTFiNGU2YjY1ZWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E7fP2fyau9swHvPlI2syFrEJKEMF1r5bF2PNIw907eE"> <img alt="Error" width="1330" src="https://private-user-images.githubusercontent.com/137357177/358936884-f9a813c5-885e-423c-89d3-8fb5e392b5dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTQ0OTEsIm5iZiI6MTcyNDM1NDE5MSwicGF0aCI6Ii8xMzczNTcxNzcvMzU4OTM2ODg0LWY5YTgxM2M1LTg4NWUtNDIzYy04OWQzLThmYjVlMzkyYjVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxOTE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzNkZWFiMTM3ODFkMWMxN2EyZjYxOGMwMTEyZDg5NzI3MTIyNGQ2OWU4MjBhOTliMDZlNjg4ODM3ZmU1YWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tqP-QUDEixeJPrsh6imBhK6boXI6yb2HH0mt-ExImoc">
> A manual update of the API's will be saved as "custom" values in the 'settings.db' and loaded when PTapp reboots. `https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/` A successful Auto-update produces "dhtInfo"/"dhtData" values in the appdata 'settings db" file: Consequently, manual inputs will not appear in the API address (drop-down lists) .. and it will throw a transient "Error" message every time PTapp is rebooted?
> 
> <img alt="Manual API" width="1333" src="https://private-user-images.githubusercontent.com/137357177/358936899-452d6b81-5015-4902-924a-39258e18289a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTQ0OTEsIm5iZiI6MTcyNDM1NDE5MSwicGF0aCI6Ii8xMzczNTcxNzcvMzU4OTM2ODk5LTQ1MmQ2YjgxLTUwMTUtNDkwMi05MjRhLTM5MjU4ZTE4Mjg5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxOTE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzZjNTc2MmZiNzlhNGZiZTY3MDk1MmIxMmRiZWIzY2Y2NWNiNDM3MTk0ZTE4Y2UwM2I4ZWU2ZTZmNDE5ZWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EhRqw7Vvg_otk_ynVVjndQI3_wWy5pLsRKtk-2vJ_Yo"> <img alt="settings db" width="1124" src="https://private-user-images.githubusercontent.com/137357177/358936913-fd973063-0d69-4e72-a98c-b1d65a614265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTQ0OTEsIm5iZiI6MTcyNDM1NDE5MSwicGF0aCI6Ii8xMzczNTcxNzcvMzU4OTM2OTEzLWZkOTczMDYzLTBkNjktNGU3Mi1hOThjLWIxZDY1YTYxNDI2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxOTE2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQwMTQzODI3NTI3ZmYxYzZhNmM0OTgyNjYwYTU5NTA2NDc5NzI1NzcxNDA4NWM2NjMwOWZhNTcxYzBlOTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sZwaoVjA0xkHbLfu_XILoJUE4LzEtimBbyJajglb8Zg">

Worked for me, thanks.

**Comment by Maybemine** [comment]
Thank you, this worked for me as well.

**Comment by overwatch3560** [comment]
what is the solution i don't understand

**Comment by grimy86** [comment]
> what is the solution i don't understand

Iirc: Settings -> API and then replace the keys there with:

https://fusme.link/, https://jfper.link/, https://uxert.link/, https://yrkde.link/

**Comment by overwatch3560** [comment]
thank you it worked for me

**Comment by overwatch3560** [comment]
it worked until yesterday @grimy86...

**Comment by dutchy1001** [comment]
@overwatch3560 
what worked until yesterday?
I dont understand what should work??
 
Movies and series are still displaying with the above API links.
Clicking the refresh button for the API's doesn't mean you get new movies/series, it means it will check IF there is a "new" API available or it can take dead ones away.

I understand that the update button (in the settings tab) still isn't working, this will stay this way untill there is a new build/release for us to download when they fix it.

So far with the given API's (https://fusme.link/, https://jfper.link/, https://uxert.link/, https://yrkde.link/) PCT still works

**Comment by Hosseinmehrfard** [comment]
thank you it worked for me

**Comment by hassanbenhzaine** [comment]
Issue still outthere (API server URLS update fail), i had to manually update the API links to:
`https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/`

Thanks [merseyV](https://github.com/merseyV)

**Comment by jphipps85** [comment]
Issue is still persisting. I was able to successfully update my APIs by manually inputting them, and the home screen does successfully show movies and shows. However, nothing actually downloads, just sits there stuck at 0KB/0KB. So while updating the APIs manually does allow the home screens to load, it doesn't actually allow anything to buffer or download....

**Comment by overwatch3560** [comment]
Is this issue gonna be fixed soon any developer that can answer ? Its pretty annoying

**Comment by dutchy1001** [comment]
With the given API links in the above posts Popcorntime still works and adds new movies.
We understand it's an issue that it wont change automatic but works when added manual.

If there is a developer that wants to take on this issue please submit a pull request (with a fix).

PS.
I don't code myself and only help with support.

**Comment by merseyV** [comment]
>If there is a developer ...

"Is there a Dev in the house?" ................................. (silence!!!)

**Comment by merseyV** [comment]
>If there is a developer ...

"Is there a Dev in the house?" .............................................. (silence!!!)

**Comment by milahu** [comment]
still an issue

> Please wait... Updating the API Server URLs
> Error: API Server URLs could not be updated


<details>
<summary>
patched popcorntime/src/app/updater.js
</summary>

```js
    Updater.updateDHT = function (e) {
        const self = this;
        if (!Settings.dht) {
            if (e && e !== 'urls') {
                self.alertIcon('error');
                self.alertMessage('error');
console.log(`Updater.updateDHT error 1`);
            }
            return;
        } else if (e && e !== 'urls') {
            self.alertIcon();
            self.alertMessage('wait');
        }
        const dht = new DHT({verify: ed.verify});
        const hash = Buffer(Settings.dht, 'hex');
        dht.once('ready', function () {
            dht.get(hash, function (err, node) {
                if (err || !node || !node.v) {
                    if (e && e !== 'urls') {
                        self.alertIcon('error');
                        self.alertMessage('error');
console.log(`Updater.updateDHT error 2: e=${e} err=${err} node=${node} Settings.dht=${Settings.dht}`);
                    }
                    return;
                }
```

</details>


```
Updater.updateDHT error 2: e=enable err=null node=null Settings.dht=a4a9ad29e303e137ecb995c50a4e104b3e8f72e5
```


`popcorntime/node_modules/butter-settings-popcorntime.app/index.js`

```
    dht: 'a4a9ad29e303e137ecb995c50a4e104b3e8f72e5',
```

`popcorntime/node_modules/butter-settings-popcorntime.app/package.json`

```
{
  "name": "butter-settings-popcorntime.app",
  "version": "0.0.10",
```

https://www.npmjs.com/package/butter-settings-popcorntime.app

> 0.0.12 • Public • Published a year ago

but `index.js` was not changed between version 0.0.10 and 0.0.12

so the issues seems to be that nobody is seeding

```
magnet:?xt=urn:btih:a4a9ad29e303e137ecb995c50a4e104b3e8f72e5&dn=popcorntime.api.servers
```

this btih is also mentioned in https://github.com/popcorn-official/popcorn-android/pull/806

> it's `a4a9ad29e303e137ecb995c50a4e104b3e8f72e5` - hash generated on server by private/public keys and uses on desktop client

so all the official popcorntime api servers (with access to the private key) seem to be gone

**Comment by merseyV** [comment]
@milahu 
Nice bit of detective work! Can't pretend to totally follow the details .. and I'm too old learn! I get the gist, though.

The patch just stops the auto-update response Error every time the PTapp opens? Doesn't just unticking the auto-update option in 'Settings' give a similar outcome?

Looks similar to, when I tried it?

**Comment by merseyV** [comment]
@milahu 
Nice bit of detective work! Can't pretend to totally follow the details .. and I'm too old learn! I get the gist, though.

And the patch just stops the auto-update response Error every time the PTapp opens? Doesn't just unticking the auto-update option in 'Settings' give a similar outcome? Looks similar to, when I tried it?

**Comment by ivan1986** [comment]
hi

need fix
https://github.com/popcorn-time-ru/dht-annoncer

on server run `node put.js` but now some work incorrect and not anounce to dht

**Comment by milahu** [comment]
> so the issues seems to be that nobody is seeding

no, i tried to fetch `a4a9ad29e303e137ecb995c50a4e104b3e8f72e5` with qbittorrent
but qbittorrent silently fails

actually this is a client issue in `popcorn-desktop`

fetching the data from DHT works, based on [dht-keyvalue](https://github.com/draeder/dht-keyvalue)

```
git clone --depth=1 https://github.com/milahu/popcorntime-get-api-servers
cd popcorntime-get-api-servers
pnpm install
./popcorntime-get-api-servers.js
```

> ```res {"server":"https://fusme.link/,https://jfper.link/,https://uxert.link/,https://yrkde.link/","git":"https://github.com/popcorn-official/popcorn-desktop/","site":"https://popcorn-time.site/","r":"PopcornTimeApp","v":"0.5.0","keys":{"os":"Butter","fanart":"ce4bba4b3cc473306c6cddb4e1cb0da4","tvdb":"80A769280C71D83B","tmdb":"ac92176abc89a80e6f5df9510e326601","trakttv":{"id":"647c69e4ed1ad13393bf6edd9d8f9fb6fe9faf405b44320a6b71ab960b4540a2","s":"f55b0a53c63af683588b47f6de94226b7572a6f83f40bd44c58a7c83fe1f2cb1"}}}```

**Comment by ivan1986** [comment]
cool, it's work
but need test on windows

**Comment by ivan1986** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/3048

**Comment by ruinetto** [comment]
Thank you very much, @merseyV. Your recommendations worked perfectly!🤩 Now we have the best BitTorrent client back.👏

_"You're my savior, man. My own personal Jesus Christ"_ 🙏

**Comment by merseyV** [comment]
>Your recommendations worked perfectly!

If you mean the workaround (manual update?). It's no longer necessary. The Devs have fixed the "Automatically update" function (server backend, I think .. not sure?). Any plaudits for steadying the ship belongs to them!

>My own personal Jesus Christ"

The last one got betrayed, crucified, speared and starved to death! Sorry (no offence!) .. think I'll give that a miss. 🤣 🤣

**Comment by merseyV** [comment]
>Your recommendations worked perfectly!

If you mean the workaround (manual update?). It's no longer necessary. The Devs have fixed the "Automatically update" function (server backend, I think .. not sure?). Any praise for steadying the ship (rightly) belongs to them!

>My own personal Jesus Christ"

The last one got betrayed, crucified, speared and starved to death! Sorry (no offence!) .. think I'll give that a miss. 🤣 🤣

**Comment by merseyV** [comment]
>Your recommendations worked perfectly!

If you mean the workaround (manual update?) .. It's no longer necessary: The Devs have fixed the "Automatically update" function (server backend, I think .. not sure?). Any praise for steadying the ship (rightly) belongs to them!

>My own personal Jesus Christ"

The last one (with that "call-sign") got betrayed, crucified, speared and starved to death! Sorry (no offence!) .. think I'll give that a miss. 🤣 🤣

**Comment by merseyV** [comment]
>Your recommendations worked perfectly!

If you mean the workaround (manual update?) .. It's no longer necessary: The Devs have fixed the "Automatically update" function (server backend, I think .. not sure?). Any accolades for steadying the ship (rightly) belongs to them!

>My own personal Jesus Christ"

The last dude (with that "call-sign") got betrayed, crucified, speared - and starved to death! Sorry (no offence!) .. think I'll give that a miss!! 🤣 🤣

**Comment by ivan1986** [comment]
> It's no longer necessary: The Devs have fixed the "Automatically update"

No, merge and revert, need merge #3055
and i can  not reopen this issue

**Comment by merseyV** [comment]
No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did to it before (#3048) it didn't need a client update .. we didn't have to do anything to the app: Auto-updating just started working again? Is it just a temporary workaround .. won't stop it happening again?

**Comment by merseyV** [comment]
No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did to it before (#3048) it didn't need a client update .. we didn't have to do anything to the app? Auto-updating just started working again? Is it just a temporary workaround, then .. won't stop it happening again without doing the merge #3055 ?

**Comment by merseyV** [comment]
>No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did to it before (#3048)  .. we didn't have to do anything to our PTapp (client)? Auto-updating just started working again. Is it just a temporary workaround (to the back-end?) .. won't stop it happening again without doing the merge #3055 ?

@kiriles90 needs a ... nudge!?

**Comment by merseyV** [comment]
>No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did to it before (#3048)  .. we didn't have to do anything to our PTapp (client)? Auto-updating just started working again (still working?). Is it just a temporary fix .. won't stop it happening again without doing the merge #3055 ?

@kiriles90 needs a ... "nudge!"?

**Comment by merseyV** [comment]
>No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did before (#3048)  .. we didn't have to do anything to our PTapp (client)? Auto-updating just started working again (still working?). It won't stop it happening again without doing the merge #3055 ?

@kiriles90 needs a ... "nudge!"?

**Comment by merseyV** [comment]
>No, @kiriles90 merge and revert, need merge https://github.com/popcorn-official/popcorn-desktop/pull/3055
and i can not reopen this issue

@ivan1986 
I've tried to follow things ... but I don't have the "smarts!"

Whatever you did before (#3048),  we didn't have to do anything to our PTapp (client) .. I assumed it was server-side? Auto-updating just started working again (still working?). It won't stop it happening again without doing the merge #3055 ?

@kiriles90 needs a ... "nudge!"?

**Comment by ivan1986** [comment]
merging same, it works, and also fix buils - app image need set arch, because in package we have prebuild for many arch

**Comment by nirodg** [comment]
For OSX latest version made a big pushback, the 0.3.10 version does not load but there is a workaround.
1. CMD + 0
2. Open `Console` and paste: `Settings.providers.movie.uri=["MovieApi?&apiURL=https://fusme.link/, https://jfper.link/, https://uxert.link/, https;//yrkde.link/"]`
3. Close the Dev Console, click on Series and again to Movies to reload.

**Comment by merseyV** [comment]
> the 0.3.10 version does not load but there is a workaround

.... why bother?
