### ISSUE TITLE
Lack of episodes and seasons

### ISSUE THREAD

**Issue by lucassa315** [popcorn-official/popcorn-desktop#580]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
24/07/2017

I would like the app, adds the seasons and missing episodes on some series, such as for example: NCIS, CSI or Hawaii 5-0. For it is sad not to be able to follow a complete series, for it lacks many episodes and seasons. Please rectify it as soon as possible.

**Comment by ChrisAlderson** [comment]
That's why the Torrent Collection feature exists. You can search for anything missing there.
