### ISSUE TITLE
OSD appearing ramdomly with subtitles on

### ISSUE THREAD

**Issue by Lelandi** [popcorn-official/popcorn-desktop#900]
Operating System Version: W7 Pro

Popcorn Time Version: 0.3.10-0

Download date: 10/nov/18

#### Expected Behaviour

OSD only shows when I move mouse or click on keyboard

#### Actual Behaviour

OSD showing ramdomly when I've active subtitles

#### Steps to reproduce the behaviour

1. Choose a movie
2. Activate subtitles PT-BR
3. OSD appearing ramdomly

**Comment by team-pct** [comment]
OSD?

**Comment by Lelandi** [comment]
On screen display.

Em qua, 5 de dez de 2018 às 19:48, team-pct <notifications@github.com>
escreveu:

**Comment by kiriles90** [comment]
@Persei08 duplicate close please
