### ISSUE TITLE
Can't Get Past Connecting Screen

### ISSUE THREAD

**Issue by runanteldat** [popcorn-official/popcorn-desktop#935]
Operating System Version:
MacOS Mojave: 10.14.2

Popcorn Time Version:
Version 0.3.10 (0.3.10)

Download date:
Dec 27th, 2018

#### Expected Behaviour
Play movie

#### Actual Behaviour
Gets stuck on connecting

#### Steps to reproduce the behaviour
1. Open Popcorn Time
2. Click on movie
3. Click 'watch now'
4. Gets stuck on connecting

This only happens with movies; I am able to watch TV shows
![screen shot 2018-12-27 at 2 58 50 pm](https://user-images.githubusercontent.com/46201712/50492847-f8562000-09e7-11e9-8a66-3ee0b5a8e465.png)

**Comment by team-pct** [comment]
Check your Firewall , ISP , and then try with VPN or different network
